### PR TITLE
Fix exception that is raised if after_commit callback hooks are absent

### PR DESCRIPTION
**Pull request by yodarjun**
This is the same issue that is fixed by https://github.com/thoughtbot/paperclip/pull/1425 but because we needed it asap, I added tests for this.

### CODE REVIEW

**Comment by maclover7** [comment]
Hi @arjunanand ! Is this still an issue? If so, can you please rebase your PR and make sure everything is passing? Thanks!

**Comment by arjunanand** [comment]
@maclover7 sure thing

**Comment by maclover7** [comment]
Hi @arjunanand! The only think left is for you to satisfy Hound's style guide complaints and you should be all set.

**Comment by maclover7** [comment]
@arjunanand One more comment left! :wink:

**Comment by arjunanand** [comment]
Hey, so I intentionally left this as single quotes to keep it uniform with
the rest of the file. I don't think it should change to double quotes
unless I can change the whole file to follow suit

**Comment by arjunanand** [comment]
@maclover7 what do you think? I think its better to keep with convention of the rest of the file.

**Comment by maclover7** [comment]
I guess it's okay if we keep it.

paging @jferris @jyurek @mike-burns

**Comment by maclover7** [comment]
Ready to merge?

paging @jferris @jyurek @mike-burns

**Comment by jyurek** [comment]
I've pulled this in. Thanks!

**Pull request closed without merging**
