### PR TITLE
no need to define version of aws-sdk

### PR DESCRIPTION
**Pull request by justanshulsharma**
#   gem 'aws-sdk'
only this change.

### CODE REVIEW

**Comment by jyurek** [comment]
I appreciate the fixes to the hashes, but if you can remove them from this PR and submit them as a separate PR, that would be great.

**Comment by justanshulsharma** [comment]
@jyurek done :+1:

**Comment by jyurek** [comment]
Nitpick: Can you fix that newline at the end of the file? Every line should end with a newline. Thanks. :)

**Comment by justanshulsharma** [comment]
@jyurek :nail_care: done

**Comment by tute** [comment]
Thanks so much!

**Comment by tute** [comment]
Merged in.

**Comment by wagenet** [comment]
Is Paperclip now compatible with v2 of the aws-sdk? A couple weeks ago it wasn't.

**Comment by wagenet** [comment]
Looks like it is. Carry on.

**Pull request closed without merging**
