### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by jyurek**
Fixes the gemspec dependencies.
Fixes failing specs.
bundle exec appriasal rake is green for me after this.

Branched off v4.2

### CODE REVIEW

**Comment by tute** [comment]
This PR doesn't contain the spec fixes from https://github.com/thoughtbot/paperclip/pull/1897?

**Comment by jyurek** [comment]
Yeah, v4.2 already has that. Must have been a weird rebase thing.

**Comment by tute** [comment]
Tell me when branches are green and I'll release next 4.2 and 4.3 versions (if you don't do it before).

**Comment by betesh** [comment]
Is the plan to merge this into master?  Before I submit the aws_v2 PR, I'd like to have all the tests passing.  Merging this to master would certainly help with that.

**Comment by jyurek** [comment]
Yes it will get merged into master. master, v4.2 and v4.3 should all be green, because we need to get new releases out. Travis is taking its sweet time though.

**Comment by jyurek** [comment]
@tute This and the v4.2 branch are green. I'll try to merge this in to master and get v4.3.0, but if you get to it first, go for it.

**Comment by tute** [comment]
> @tute This and the v4.2 branch are green. I'll try to merge this in to master and get v4.3.0, but if you get to it first, go for it.

Released 4.2.3, and pushed the merge: https://github.com/thoughtbot/paperclip/commit/397457c4d50e2e426c55d5ed8b405644a7d9b37a. We can release 4.3.0 on green CI.

**Comment by betesh** [comment]
Thanks.  I rebased aws_v2 onto master and will open a PR if Travis approves.

**Pull request merged**
