### PR TITLE
Introduce `add_validation_errors_to` option

### PR DESCRIPTION
**Pull request by brendon**
Valid values for `add_validation_errors_to` are `:attribute`, `:base`,
or `:both`.

The option is globally set to `:both` that retains the existing
behaviour of adding validation errors to both the attribute and the
model base.

Closes: #1367
References: #2090, #2040

### CODE REVIEW

**Comment by brendon** [comment]
FYI, the tests that are failing were failing before I commenced work on this PR. The spec suite still runs green.

**Comment by brendon** [comment]
And RE Hound, I stuck with the code style exhibited by the existing code. Let me know if you want me to change it to conform to Hound.

**Comment by brendon** [comment]
@tute, I've pulled in your suite fixes and everything's green now.

**Comment by brendon** [comment]
Hi @tute, would we be able to get some movement on this PR? :)

**Comment by tute** [comment]
I'm not doing much paperclip nowadays. Maybe @sikachu is?

**Comment by brendon** [comment]
Thanks @tute, I'll wait to hear from him :)

**Comment by brendon** [comment]
Hi @tute, looks like @sikachu isn't responding either. I'm really keen to stop using my fork for this fix. The tests all pass and if you take a quick look at the code I'm sure you'll find it's fairly straightforward and doesn't change the existing default behaviour, it just allows one to override it if necessary in either direction. I spent quite a bit of time making sure this PR would be an easy one to merge and that it took into consideration all the feedback on previous failed PR's for this issue. It'd be great if someone could take a few minutes to check it over and merge it or let me know what changes need making in order for it to be accepted :)

**Comment by brendon** [comment]
@tute, @sikachu could you let me know who is currently maintaining `paperclip`?

**Comment by rocket-turtle** [comment]
Hello,

thank you for the great work on this gem.
We also had a lot of problems with duplicate Error Messages and endet up Monkey patching the Validators. With this Solution we could get rid of these patches. So we would be happy to see this in a new Version.

A small problem is if you do not add the error to `"#{attribute}_file_size"` the `validate_attachment_size` matcher doesn't work any more.

https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/matchers/validate_attachment_size_matcher.rb

**Comment by brendon** [comment]
Hi @rocket-turtle, I wouldn't hold out much hope for this getting accepted any time soon. I don't think there's much, if any, activity on Paperclip anymore and no one seems willing to look at new PR's.

Can you elaborate on the problem you reported? I'm not quite getting it yet :) I'd be happy to fix it in my branch.

**Comment by rocket-turtle** [comment]
Hi @brendon,

I thought so as well but want to share the Information anyway.
Here is the Test for the Problem I described.

paperclip/spec/paperclip/matchers/validate_attachment_size_matcher_spec.rb:36
```
    context "add_validation_errors_to = :base" do
      before do
        Paperclip.options[:add_validation_errors_to] = :base
      end

      after do
        Paperclip.options[:add_validation_errors_to] = :both
      end

      it 'accepts a class with a validation that matches' do
        Dummy.validates_attachment_size :avatar, in: 256..1024
        expect(matcher.in(256..1024)).to accept(Dummy)
      end
    end
```

**Comment by brendon** [comment]
Thanks @rocket-turtle :) I've had a bit of a look. I suspect it might be to do with the way `shoulda-matchers` does its thing. Is it looking for a validation error on the attribute in order to pass? If so, that would explain it.

I don't think that needs further testing because we know the model will still fail to validate because of the other validator spec's. What do you think?

**Comment by rocket-turtle** [comment]
yes the matcher `validate_attachment_size` provided by paperclip checks for `"#{attribute}_file_size"` if `Paperclip.options[:add_validation_errors_to] = :base` is configured this helper does not work any more. So you can't use it in tests any more.

I don't understand your last sentence.

**Comment by brendon** [comment]
I was meaning (in the last sentence) that since we're already testing the validation via the shoulda matcher in the case of `:both`, and because we're also testing that errors are added to `:attribute`, `:both`, or `:base` in the other tests in my PR, then it's probably not necessary to test this scenario here.

I suppose we could modify the matcher or add a new one though.

**Comment by brendon** [comment]
@rocket-turtle, I've added you as a collaborator on my fork, so if you want to modify the matcher to still work in the `:base` instance you're more than welcome :D

Given no one seems to be wanting to look at the PR, I don't waste any more of my time on it to be frank.

**Comment by rafaelss95** [comment]
This PR is really great. Any chance to get this merged?

**Comment by brendon** [comment]
Sadly, it almost looks as if Paperclip is dead. No significant updates since last year. No one willing to look at PR's. I'm not sure what to do given it's managed by a development company.

**Comment by rafaelss95** [comment]
Yes, unfortunately it's true. Is it an impression or is it true that most (if not all) the **awesome** projects developed by `thoughtbot` are being discontinued?

**Comment by brendon** [comment]
I'd assume they're not being discontinued but perhaps the focus there has shifted? In any event, it might be time to appoint some community maintainers if the existing ones don't have the time to continue development.

**Comment by brendon** [comment]
@geoffharcourt would you mind taking a look at this PR for me?

**Comment by sidraval** [comment]
We are in the process of deprecating paperclip, and so are closing PRs that aren't immediate bug fixes or documentation updates. Thanks for your contribution, we regret not tending to it!

**Comment by brendon** [comment]
@sidraval, have thoughtbot considered allowing members of the community to maintain paperclip? Or will work be done on a migration path to the native rails solution in 5.2? :)

**Pull request closed without merging**
