### PR TITLE
Added config to bypass media type spoofing check

### PR DESCRIPTION
**Pull request by rystraum**
https://github.com/thoughtbot/paperclip/issues/1924

Though a better implementation for this would be doing this on a per
model basis.

### CODE REVIEW

**Comment by jtrost** [comment]
This is great! I think `:do_not_do_media_type_spoofing_detection` is too long and verbose for a configuration key. It could be more concisely named `:detect_media_type_spoofing`.

**Comment by rystraum** [comment]
@jtrost I opted for a verbose configuration key, following Paperclip's `do_not_validate_attachment_file_type` to tell the developer that this isn't a recommended setting, but you can change it if you really want.

**Comment by jtrost** [comment]
Thanks for the explanation!

**Comment by kirushanth-sakthivetpillai** [comment]
An alternative:

Paperclip has content-type checking and media-type checking. Both seem to do the same thing using `file -b --mime`.

Media-type checking uses the global config of `content_type_mappings`. However, sometimes you want per-model exceptions. Paperclip provides the option for it but not well documented. I got it from the source here:
https://github.com/thoughtbot/paperclip/blob/v4.3/lib/paperclip/has_attached_file.rb#L83

You can do the following to control media-type and content-type checking:

```
class PaperclipModel < ActiveRecord::Base

   has_attached_file :attachment, { validate_media_type: false }

  validates_attachment :attachment, {
     # tweak as desired
     content_type: { content_type: ["text/csv", "text/plain", Paperclip::ContentTypeDetector::SENSIBLE_DEFAULT] }
  }
end
```

**Comment by saghaulor** [comment]
@rystraum Paperclip can disable media type spoof checking at a per model level with the `validate_media_type` option.

**Pull request closed without merging**
