### PR TITLE
Add Code Climate Config

### PR DESCRIPTION
**Pull request by pbrisbin**
Hello friends,

Earlier today, we unintentionally deleted this repository from Code Climate while doing some administrative cleanup. I'm really sorry this happened and please know we can get the data back if that's what you'd like, but we were wondering if you'd rather have the repository re-added using our new Platform.

The one hiccup is that your rubocop config is too old for our engine to use, so analyses on the new Platform don't succeed. This PR corrects that (and tries not to step on Hound in the process), making the repository suitable for adding again on Code Climate.

Please let me know what you think.

### CODE REVIEW

**Comment by tute** [comment]
Hi @pbrisbin! Thank you. Can we update `.hound.yml` instead of having two copies? Thanks!

**Comment by pbrisbin** [comment]
Hey @tute , we can definitely do that instead. We were trying to be careful not to impact Hound with this change.

**Comment by tute** [comment]
@gylaz if we update the `.hound.yml` configuration with the following patch, will Hound continue to properly work for paperclip? Thank you!

```diff
diff --git a/.hound.yml b/.hound.yml
index 656228d..8502803 100644
--- a/.hound.yml
+++ b/.hound.yml
@@ -20,7 +20,8 @@ AllCops:
     - "db/schema.rb"
     - 'vendor/**/*'
     - 'gemfiles/vendor/**/*'
-  RunRailsCops: false
+  Rails:
+    Enabled: false
   DisplayCopNames: false
   StyleGuideCopsOnly: false
 Style/AccessModifierIndentation:
@@ -434,7 +435,7 @@ Style/TrailingBlankLines:
   SupportedStyles:
   - final_newline
   - final_blank_line
-Style/TrailingComma:
+Style/TrailingCommaInLiteral:
   Description: Checks for trailing comma in parameter lists and literals.
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-trailing-array-commas
   Enabled: false
@@ -560,11 +561,6 @@ Rails/ActionFilter:
   - filter
   Include:
   - app/controllers/**/*.rb
-Rails/DefaultScope:
-  Description: Checks if the argument passed to default_scope is a block.
-  Enabled: true
-  Include:
-  - app/models/**/*.rb
 Rails/HasAndBelongsToMany:
   Description: Prefer has_many :through to has_and_belongs_to_many.
   Enabled: true
@@ -685,7 +681,7 @@ Style/DefWithParentheses:
   Description: Use def with parentheses when there are arguments.
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#method-parens
   Enabled: true
-Style/DeprecatedHashMethods:
+Style/PreferredHashMethods:
   Description: Checks for use of deprecated Hash methods.
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#hash-key
   Enabled: false
@@ -840,7 +836,7 @@ Style/SelfAssignment:
     used.
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#self-assignment
   Enabled: false
-Style/SingleSpaceBeforeFirstArg:
+Style/SpaceBeforeFirstArg:
   Description: Checks that exactly one space is used between a method name and the
     first argument for method calls without parentheses.
   Enabled: true
@@ -852,7 +848,7 @@ Style/SpaceAfterComma:
   Description: Use spaces after commas.
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#spaces-operators
   Enabled: true
-Style/SpaceAfterControlKeyword:
+Style/SpaceAroundKeyword:
   Description: Use spaces after if/elsif/unless/while/until/case/when.
   Enabled: true
 Style/SpaceAfterMethodName:
@@ -881,9 +877,6 @@ Style/SpaceAroundOperators:
   Description: Use spaces around operators.
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#spaces-operators
   Enabled: true
-Style/SpaceBeforeModifierKeyword:
-  Description: Put a space before the modifier keyword.
-  Enabled: true
 Style/SpaceInsideBrackets:
   Description: No spaces after [ or before ].
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-spaces-braces
@@ -923,10 +916,6 @@ Style/UnneededPercentQ:
   Description: Checks for %q/%Q when single quotes or double quotes would do.
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#percent-q
   Enabled: true
-Style/UnneededPercentX:
-  Description: Checks for %x when `` would do.
-  StyleGuide: https://github.com/bbatsov/ruby-style-guide#percent-x
-  Enabled: true
 Style/VariableInterpolation:
   Description: Don't interpolate global, instance and class variables directly in
     strings.
```

**Comment by gylaz** [comment]
@tute How was the above generated? Hound is currently on 0.39 version of RuboCop, so `PreferredHashMethods` key isn't available in that version.

**Comment by pbrisbin** [comment]
@tute would you like me to re-work this PR to be that more minimal patch you've posted?

@gylaz the change in this PR was generated with `codeclimate init`. Our engine runs Rubocop  0.41.2. It looks like @tute was nice enough to figure out and address just the incompatible cops in his proposed patch.

It sounds like the `PreferredHashMethods` is the only problematic cop? If so, maybe there's a solution here with a `.rubocop.yml` that specifies all but it (and is compatible with both 0.39 and 0.41), then separate `.hound.yml` and `.cc-rubocop.yml` files that both inherit from it, then specify the 0.39 and 0.41 compatible versions of that cop. Or maybe that's too complicated...

**Comment by tute** [comment]
We can skip `PreferredHashMethods` for both.

**Comment by tute** [comment]
I'd do it for you today @pbrisbin, but I'll let you do it so you make sure it works in Code Climate. Thanks a lot!

**Comment by pbrisbin** [comment]
@tute this should be all set. I've confirmed the updated configuration succeeds with `codeclimate analyze`, so once this merges to master we'll be able to successfully re-add the project to Code Climate using the new Platform.

**Comment by tute** [comment]
It looks like Hound CI won't recognize cops `Style/Blocks` and `Style/UnneededPercentX`, nor parameters `AllCops:Rails` and `Style/RegexpLiteral:MaxSlashes`.

@gylaz will Hound anyway work, or should we do something about those unrecognized values?

Thank you!

```
% rubocop -v
0.39.0
% rubocop --config .hound.yml
/Users/tutec/Sites/thoughtbot/paperclip/paperclip/.hound.yml: Lint/SpaceBeforeFirstArg has the wrong namespace - should be Style
Warning: unrecognized cop Style/Blocks found in /Users/tutec/Sites/thoughtbot/paperclip/paperclip/.hound.yml
Warning: unrecognized cop Style/UnneededPercentX found in /Users/tutec/Sites/thoughtbot/paperclip/paperclip/.hound.yml
Warning: unrecognized parameter AllCops:Rails found in /Users/tutec/Sites/thoughtbot/paperclip/paperclip/.hound.yml
Warning: unrecognized parameter Style/RegexpLiteral:MaxSlashes found in /Users/tutec/Sites/thoughtbot/paperclip/paperclip/.hound.yml
```

**Comment by tute** [comment]
(There is also the namespace error)

**Comment by pbrisbin** [comment]
Hey @tute is there anything you need from me to move this forward?

**Comment by gylaz** [comment]
@tute Seems this project is using a legacy style of `hound.yml`. You can see how to configure it at houndci.com/configuration

The unrecognized values should be silently ignored by RuboCop.

**Comment by tute** [comment]
Thank you all!

**Pull request merged**
