### PR TITLE
Remove duplication by reusing existing method.

### PR DESCRIPTION
**Pull request by airblade**

### CODE REVIEW

**Comment by airblade** [comment]
No new tests because this is a small refactoring.

**Comment by tute** [comment]
Thanks! 

This is a big, brittle class with shared state and way too many conditionals. I'd rather rewrite it form scratch or drop v1 support altogether, than perform local iterative improvements.

This is a small improvement indeed, and I think we can safely merge it. Will wait until `master` has a green CI before merging this in.

**Comment by tute** [comment]
Can you please rebase on top of latest master, And fix CI? Thank you!

**Comment by airblade** [comment]
I just rebased this on top of the latest master.

**Comment by tute** [comment]
Thank you!

**Pull request merged**
