### PR TITLE
Prepare release for v5.0.0

### PR DESCRIPTION
**Pull request by tute**
There are two backward incompatible changes.

cc @jyurek @iwz

### CODE REVIEW

**Comment by maclover7** [comment]
Should we hold off on releasing this until Rails 5 lands, I think we are planning on dropping support for 3.2 as apart of that release?

**Comment by iwz** [comment]
There was a fix for Rails 3.2 I'd like to get into a  release. Maybe we can
cut from there?

**Comment by tute** [comment]
> There was a fix for Rails 3.2 I'd like to get into a release. Maybe we can cut from there?

Sounds good. master got so many changes, including two backward incompatible ones. We could do a patch release with your commit. What is its SHA?

**Comment by tute** [comment]
> I think we are planning on dropping support for 3.2 as apart of that release?

Yes.

> Should we hold off on releasing this until Rails 5 lands

We could hold off the backwards incompatible changes, but a minor version with everything else would be healthy I think. Let's ask @jyurek!

**Comment by jyurek** [comment]
I think a minor version without the backwards incompatible changes are probably best right now, and we can discuss things like the MD5->SHA change.

**Comment by iwz** [comment]
@tute the SHA I'm looking for is c740fb171fe2f88c60b999d2a1c2122f2b8f43e9

**Comment by tute** [comment]
After we release https://github.com/thoughtbot/paperclip/pull/1995, I'll merge master into it, and rebase this branch when we decide it's time to do the major release. Thank you for your input.

**Comment by greggawatt** [comment]
It seems like #1995 was merged in, what's the status on this?

**Comment by tute** [comment]
We'll release the major version after Rails 5 is out. The commit that fixed a Rails 3.2 regression is already out.

**Pull request closed without merging**
