### PR TITLE
Removes Rails 3.2 and 4.1 support

### PR DESCRIPTION
**Pull request by tute**
In preparation for Rails 5, which, when it is released, will make Rails
3.2 and 4.1 unsupported.

See:

* http://weblog.rubyonrails.org/2015/12/18/Rails-5-0-beta1/
* https://github.com/thoughtbot/paperclip/issues/2049

### CODE REVIEW

**Comment by maclover7** [comment]
@tute - We're going to have to revert this for right now. We need to get deprecations into a 4.x point release before we go ahead with any breaking changes :)

**Comment by maclover7** [comment]
Wait -- never mind. Didn't realize master is already backwards incompatible, and that we are using the `v4.3` branch for 4.3.x releases. Please disregard :)

**Comment by tute** [comment]
v4 is its own branch, and lives behind master. This is fine, the 4.2.x cut will be done with the warnings.

**Comment by tute** [comment]
Right. :+1:

**Comment by maclover7** [comment]
:+1:

**Pull request merged**
