### PR TITLE
Fix a build

### PR DESCRIPTION
**Pull request by morgoth**
let's see what Travis says

### CODE REVIEW

**Comment by morgoth** [comment]
@geoffharcourt This fixes the build again. I didn't dig enough to find a real cause - debugging cucumber is painful... ;-)
Looking at recent failures, I would be for checking in `Gemfile.lock` into repo, to avoid such situations, as it slows down development a lot.

It's also now the recommended workflow by bundler, vide https://github.com/bundler/bundler/issues/5879

**Comment by morgoth** [comment]
@geoffharcourt did you have some time to look into it maybe? :)

**Comment by geoffharcourt** [comment]
Hi @morgoth I hadn't had time recently to do a thorough check. This looks good to me, let's merge and see if this opens things up for other PRs to move forward.

**Comment by geoffharcourt** [comment]
@morgoth can you update the commit message so that it's clear you did? I'll merge after that.

**Comment by morgoth** [comment]
@geoffharcourt Just did and the build is still green

**Comment by geoffharcourt** [comment]
Thank you for your work and your patience!

**Pull request merged**
