### PR TITLE
Add deprecation warnings for aws-sdk < 2 and active record < 4.2

### PR DESCRIPTION
**Pull request by kevcha**
Following https://github.com/thoughtbot/paperclip/pull/2095

### CODE REVIEW

**Comment by maclover7** [comment]
Waiting on Travis, and then I think we can merge.

**Comment by kevcha** [comment]
Hum, that's not what I expected. Since it's 2 am for me now, I'll take a more deeper look at that tomorrow :)

**Comment by kevcha** [comment]
I'll squash those commits if you think it's good

**Comment by maclover7** [comment]
Sure - please squash.

**Comment by kevcha** [comment]
Done :)

**Comment by maclover7** [comment]
:+1: Thank you for your contribution!

**Comment by maclover7** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
