### PR TITLE
WIP: randomly generate tempfile names

### PR DESCRIPTION
**Pull request by alvarezwendell04**

### CODE REVIEW

**Comment by jyurek** [comment]
@alvarezwendell04: This was @sikachu's WIP branch. Why did you make a PR for it?

@sikachu: Are there other things you wanted to do here, or would you consider this for merging? Also, does the fact that the names can't be retrieved from the Tempfile once you make it have an effect on using them? Do/can files get lost?

**Comment by sikachu** [comment]
@jyurek Let me check the code. I'm not sure why I left it like that, but I must have ran into something.

**Comment by jyurek** [comment]
Hey @sikachu what's the status of this?

**Comment by tute** [comment]
@sikachu didn't open a PR for his work, so I assume it wasn't ready? If it was, I'll let him reopen a clean and rebased PR. Thank you!

**Pull request closed without merging**
