### PR TITLE
Regression fix: original file could be unlinked in post_process_style

### PR DESCRIPTION
**Pull request by tiegz**
https://github.com/thoughtbot/paperclip/commit/87cebf991ac49bb3f655e1e7d834c203217583dd added an `intermediate_files` local var in `Paperclip::Attachment#post_process_style` to collect temp files and then ensure they get unlinked at the end of `post_process_style()`.

But in this scenario [when a processor just returns `@file`]:

``` ruby
class Paperclip::Foo
  def make
    # ... do something with the file ...
    @file
  end
end

has_attached_file :image, {
  processors: [:foo],
  styles: {
    full: "200x200",
    thumb: "100x100"
  }
}
```

1) `post_process_style` is run for the `:full` style 
  * `Paperclip::Foo.make` is run on `:full`
  * the original file (aka `queued_for_write[:original]`) gets added to `intermediate_files`
  * when finished, files in `intermediate_files` are unlinked, including the original file

2) `post_process_style` is run for the `:thumb` style
  * `Paperclip::Foo.make` is run on `:thumb`  :bomb: :boom: `make` fails because the original file that was passed to it has been unlinked

NB I tried to write a spec for this, but it proved a little difficult. Hopefully this change makes enough sense when seen?

Thanks :sunrise:

### CODE REVIEW

**Comment by jyurek** [comment]
Sounds good to me, but can you write a spec for it? Thanks.

**Comment by tiegz** [comment]
@jyurek specs added!

**Comment by dmitry** [comment]
Please make sure this will never happen again: https://github.com/thoughtbot/paperclip/issues/1326

**Comment by tute** [comment]
Is this good for merge, @jyurek?

**Comment by Fernan2** [comment]
I had my /tmp directory full of crap generated by paperclip... and this seems to be the solution, could you please merge it?

(that's not a trivial issue, I had to delete that crap manually because the server was about of running out of free disk)

**Comment by dmitry** [comment]
@Fernan2 we've stuck the same issue with ext4, it has limitation of 4M files in on path. But we fixed it by changing the ENV variable for the resque: https://github.com/resque/resque/issues/1167

**Comment by tute** [comment]
Thank you all!

**Comment by tiegz** [comment]
Hmm, without merging this the regression still exists, and it's still possible for the `:original` to be unlinked before another style attempts to reference it. I thought my change was safe because `after_flush_writes` should clear the original -- is that not the case?

**Pull request closed without merging**
