### PR TITLE
Ignore invalid Content-Disposition header

### LINKED ISSUE #2283: NoMethodFound exception on invalid Content-Disposition header
Tried to upload file by URL

The server returned 
``"content-disposition"=>"inline; filename=blabla.jpg"``
filename must be quoted so the header is invalid
regexp ``match(/filename="([^"]*)"/)`` finds nothing here so ``match(...)[1]`` fails

I think that it's good to just ignore it instead of trying to parse it anyway

### PR DESCRIPTION
**Pull request by sandfoxme**
Here is one way to fix #2283

### CODE REVIEW

**Comment by tute** [comment]
There is no behavior change now. Does this fix #2283?

**Comment by sandfoxme** [comment]
Yes, the exception is now gone

**Comment by tute** [comment]
Thank you!

**Comment by maletor** [comment]
Is it possible we are almost ready to cut a new release with this regression fix?

**Comment by jbielick** [comment]
Is there a chance this could be backported to 4.3?

**Comment by phbernard** [comment]
As an aside, [a Content-Disposition is allowed to not contain a filename component](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition). So strictly speaking this fix is not only for "invalid Content-Disposition", making it even more useful.

I backup @maletor, it would be great to have a new release with this fix.

**Pull request merged**
