### PR TITLE
Update example to add mime-types to file extensions

### LINKED ISSUE #1737: update doc: MIME::Types#index_extensions is deprecated and will be private.
The warning shows up when I copy it from document. 
But I don't find method to avoid it

mime-types (2.4.3)

### PR DESCRIPTION
**Pull request by bdewater**
Fixes #1737.

### CODE REVIEW

**Comment by tute** [comment]
Thanks! Since when do we need this doc change? Can you please add context to your commit message, with a link to the change? Then we'll merge. Thank you!

**Comment by bdewater** [comment]
I'm not sure since when that gem started giving those warnings - the old method still works on version <3 but with master now targeting >= 1.16 && < 4 it seemed like time to move away from deprecated functionality. I'll update the commit message in a couple of hours.

**Comment by bdewater** [comment]
Updated :)!

**Comment by tute** [comment]
Thank you!

**Pull request merged**
