### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by lemuelbarango**
Removed the comma on line 54: 'based on size and presence, if required' -> 'based on size and presence if required'
Removed the comma on line 166: 'ahead of the latest released version, if you're' -> 'ahead of the latest released version if you're'
Added a comma on line 571: 'was chosen because on standard Capistrano deployments' -> 'was chosen because, on standard Capistrano deployments'
Changed line 627: 'For backwards compatibility reasons' -> 'For backward compatibility reasons'
Changed line 822: 'By default Paperclip outputs ... in to your' -> 'By default, Paperclip outputs ... into your'

### CODE REVIEW

**Comment by maclover7** [comment]
Thanks for these grammar fixes! Would it be okay if we left the comma in line 54? Doesn't read right to me without it. Thanks again for your PR! :)

**Comment by lemuelbarango** [comment]
Yeah is cool

**Comment by maclover7** [comment]
Cool -- can you update the PR? Thanks again!

**Comment by tute** [comment]
:+1:. Feel free to rebase and merge Jon (adding `[fixes #2032]` to keep the link) or just push the green button. Thank you both!

**Comment by maclover7** [comment]
@lemuelbarango, sorry, can you rebase on master please? Travis build is failing for some reason.

**Comment by tute** [comment]
> Travis build is failing for some reason

Just restarted the jobs. In this matrix we sometimes get random timeouts, or similar. On commits that don't change code we can add `[skip ci]` to the commit message to avoid running it (and it potentially failing).

**Comment by maclover7** [comment]
Bingo, all set @lemuelbarango. Thanks for your patience! :heart:

**Pull request merged**
