### PR TITLE
Documentation TOC

### PR DESCRIPTION
**Pull request by maclover7**
Companion PR for #1854.

### CODE REVIEW

**Comment by maclover7** [comment]
@tute Is this ready to go?

**Comment by tute** [comment]
That is great! Go ahead, rebase `master` onto `maclover7-toc` (we don't use the merge button).

Did you do it by hand? Ideally it would be almost-automatically generated, so when sections changes calculating the diff is easy. I noticed that with current markup sections get skewed. It's not really important, just a nice to have.

Anyhow, rebase away! :+1:

**Comment by maclover7** [comment]
Yeah, I did it by hand. Why do we not merge PRs?

**Comment by tute** [comment]
I think this is mostly a style decision, and it might have some interesting technicalities while trying to revert commits (versus reverting trees merges). A rationale can be found in https://robots.thoughtbot.com/rebase-like-a-boss.

**Comment by tute** [comment]
Thank you!

**Pull request merged**
