### PR TITLE
Relax mimemagic version constraint to ~> 0.3.0

### PR DESCRIPTION
**Pull request by jaredbeck**
mimemagic 0.3.1 has been released.

### CODE REVIEW

**Comment by jaredbeck** [comment]
@maclover7 @tute @jyurek can someone take a look at this, please? Thanks!

**Comment by maclover7** [comment]
Sorry for the wait. Thanks for your contribution!

**Comment by maclover7** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by jaredbeck** [comment]
Thanks Jon!

**Comment by knightq** [comment]
Can this be ported also on v4.3 branch (so that it will be included in the next `4.3.4` minor release)?

Thank you!

**Comment by maclover7** [comment]
I believe upgrading the version requirement counts as a breaking change, so I can't backporting that to v4.3.

**Comment by knightq** [comment]
I would agree with you, if we were talking of a gem that does not follow a semantic versioning (as mimemagic does, instead) and we were not talking of a build upgrade (`s.add_dependency('mimemagic', '~> 0.3.0')`)

With these premises, I do not think that it would be a _breaking change_, since it will not brake anything (have a look also at the [changelog](https://github.com/minad/mimemagic/compare/v0.3.0...master) of mimemagic)

Anyway, the decision is clearly up to you...

**Comment by jaredbeck** [comment]
> I believe upgrading the version requirement counts as a breaking change

I've seen a few discussions about this exact versioning question.  Here are a few:

- https://github.com/mojombo/semver/issues/148  
- https://github.com/haml/haml/issues/761
- https://github.com/airblade/paper_trail/pull/540

There does not seem to be any consensus that I can see, so we are left to use our own judgement :)

**Comment by jaredbeck** [comment]
Jon, can you backport this to the https://github.com/thoughtbot/paperclip/tree/v4.3 branch please?

**Comment by maclover7** [comment]
As said earlier, I think this is a breaking change, so I can't backport to a 4.3.x version. This will be apart of the upcoming 5.0 release.

**Comment by jaredbeck** [comment]
OK, no big deal, thanks. I look forward to the 5.0 release.

**Pull request merged**
