### PR TITLE
Adding new option :relative to :url S3 storage

### PR DESCRIPTION
**Pull request by gmontard**
I'm following this issue #1829 

**Usecase:**
I want to still rely on ActionController::Base.asset_host to manage my absolute URL but the current option _:asset_host_ append rails asset pipeline path (/assets) which is not valid in this scenario.

Thanks.

### CODE REVIEW

**Comment by jyurek** [comment]
Seems straightforward enough. Can you clean up the Hound issues, though? Thanks.

**Comment by gmontard** [comment]
Hello @jyurek,

I managed all Hound issues unless one which is mostly not from my code.

Thanks.

**Comment by jyurek** [comment]
@gmontard, there's a problem with the travis tests. Can you check it out?

**Comment by tute** [comment]
ping @gmontard. Thanks!

**Comment by tute** [comment]
@gmontard are you interested in moving this forward? Thanks!

**Comment by gmontard** [comment]
Hello @tute - Sadly I don't have much time anymore to work on this as neither I have the need.. 

Thanks

**Comment by sidraval** [comment]
We are in the process of deprecating paperclip, and so are closing PRs that aren't immediate bug fixes or documentation updates. Thanks for your contribution, we regret not tending to it!

**Pull request closed without merging**
