### PR TITLE
Add global and per validation options for duplicating errors on base …

### PR DESCRIPTION
**Pull request by aouji**
…attribute.

Adds an option to turn duplication of error messages on the base attribute on/off globally or per validation. The option is on globally by default.

### CODE REVIEW

**Comment by aouji** [comment]
This should fix #2040 and #1367 .

**Comment by aouji** [comment]
Let me know if the Hound has to be convinced 100%.

**Comment by aouji** [comment]
@tute Can you please let me know if I am taking the right approach here? Just wondering if this is in line with what thoughtbot would want and if I should do another round of addressing the houndci-bot comments.

BTW, I think the `errors.delete(:file)` approach mentioned in https://github.com/thoughtbot/paperclip/pull/1554 has the side effect of removing errors that are not duplicated (e.g. errors from the presence and spoof detection validations).

**Comment by tute** [comment]
@aouji sorry I didn't get to it this week. Hopefully next one! Thank you very much for your work.

**Comment by aouji** [comment]
Sorry to ping you again @tute . Have you had time to take a look at this?

**Comment by tute** [comment]
Thanks for pinging @aouji. Not yet, hopefully next week.

**Comment by tute** [comment]
@aouji I just closed https://github.com/thoughtbot/paperclip/pull/1554#issuecomment-200666161 with that linked comment that states a solution for client applications that need to override this behavior, and my rationale on why I think that PR (solving this issue) should not be merged into paperclip.

Your PR adds 300 lines of code, and the ability for users to turn off the duplication of error messages onto base. It doesn't take into account the users who actually want to have the errors on base, but not on each field. So it adds complexity to the project, but it doesn't solve the underlying issue (or it does, for one of the three different use cases).

I appreciate your time and effort invested in triaging this issue, and proposing and sharing a fix with us. But I don't think this PR is a good alternative solution for current paperclip behavior, and thus I will close it as well.

As stated in the other PR, I'll consider a fix that, without adding much complexity, takes care of both use cases.

Thank you very much, again. ❤️

**Comment by aouji** [comment]
Thanks for the detailed explanation @tute! 

Regarding the ~300 lines of change in the pull, ~30 lines are code changes and the rest are tests. That being said, you are completely right about the use cases. My code does not cover users wanting to keep base but remove the other ones. I might make another try at covering all scenarios if I find the time.

Thanks for maintaining paperclip. Without it a lot of rails apps - including mine - will be in big trouble!

**Pull request closed without merging**
