### PR TITLE
The long awaited AWS v2 support PR

### PR DESCRIPTION
**Pull request by betesh**
Thank you to @davetchen, who really did most of the work here.

### CODE REVIEW

**Comment by tute** [comment]
I was about to release v4.3, but this should part of the release, right @jyurek?

**Comment by tute** [comment]
I'd love if we could use an adapter instead of adding conditionals everywhere we use AWS in the code.

**Comment by tute** [comment]
There's too many releases in 4.3, will release anyway, and we can add this in 4.4.

**Comment by betesh** [comment]
> I'd love if we could use an adapter instead of adding conditionals everywhere we use AWS in the code.

@tute, @trevorrowe proposed something similar (https://github.com/thoughtbot/paperclip/issues/1764#issuecomment-103325634) but proposed leaving the conditions in place (https://github.com/thoughtbot/paperclip/issues/1764#issuecomment-103569165) since AWS v1 will soon be deprecated anyway.

**Comment by betesh** [comment]
@tute  FYI I have added more Gemfiles so that travis tests both AWS versions.  Everything is passing on both versions.

This makes it very safe to add additional features to this branch that are specific to AWS v2, as long those features are accompanied by appropriate tests.  Would any of the #1730 contributors like to try merging the new functionality there into this PR?

**Comment by tute** [comment]
cc @jyurek to merge this PR

**Comment by jyurek** [comment]
I had some local failures related to regions, so I put in a fix for them, but this is merged. There are things I would clean up in the code, but I can't let that stop this PR at this point. We can fix them in the future. Thank you very much for working on this.

**Comment by tute** [comment]
Yay! :tada: :balloon: :clap: 

Gonna go out in 4.4.

**Comment by jyurek** [comment]
@betesh There are failures on Travis. Can you take a look at them and see if there's anything that jumps out at you? https://travis-ci.org/thoughtbot/paperclip/jobs/76525495

**Comment by betesh** [comment]
@jyurek What was the goal of b8221c6b9f9e4c616973b859a8ad0b05f7511372?  If I understand correctly, it's to make the attachment URL use s3_doman_url by default if an s3_region has been defined.  Since s3_region is defined for AWS v2 in all the S3 specs (there's no other way to make them pass), we need either: 

1) if-then logic within each test to handle AWS v2 differently than v1 -- I just pushed a commit attempting this, we'll see if it works...

**OR**

2)  to consider those tests inapplicable to AWS v2, and just wrap the whole thing if an `if defined(::AWS)`

**Comment by jyurek** [comment]
The goal was to get my local tests passing, but turns out I was wrong. I reverted and it's all good now. My bad. :)

**Comment by betesh** [comment]
Just curious, do you mean tests in a rails app that uses paperclip, or the S3 Live specs?

**Comment by jyurek** [comment]
I mean the Paperclip specs themselves. Though the failure I saw was in the feature specs, so technically it was an app that uses paperclip. But that's nitpicking.

**Comment by nickrivadeneira** [comment]
@tute Looks like v4.4 is being skipped - will this officially be released in v5?

**Comment by tute** [comment]
> @tute Looks like v4.4 is being skipped - will this officially be released in v5?

Yes. If you are on Rails 4.2 you can grab the latest v5 beta.

**Pull request closed without merging**
