### PR TITLE
Rspec 3 Use `failure_message`

### PR DESCRIPTION
**Pull request by soramugi**
Deprecation Warnings:

```
`failure_message_for_should` is deprecated. Use `failure_message` instead. Called from /Users/mugi/git/paperclip/spec/support/matchers/have_column.rb:11:in `block in <top (required)>'.
```

### CODE REVIEW

**Comment by maclover7** [comment]
Hi @soramugi ! Is this still an issue? If so, can you please rebase your PR and make sure everything is passing? Thanks!

**Comment by jyurek** [comment]
Does this change require RSpec 3, or is it backwards compatible? If it's not, can you add a version check?

**Comment by soramugi** [comment]
@jyurek fix , added a backward-compatible changes.

**Comment by jyurek** [comment]
I pulled this in and cleaned it up a little. Thanks!

**Pull request closed without merging**
