### PR TITLE
Remove deprecations

### PR DESCRIPTION
**Pull request by maclover7**
This will be released in v4.3.5.

### CODE REVIEW

**Comment by maclover7** [comment]
Travis is green -- merging!

**Comment by sikachu** [comment]
@maclover7 thanks!

**Comment by tute** [comment]
This should have been released in v5, not 4.3, right? To help people upgrade (think rspec 2.99).

**Comment by tute** [comment]
Yes, people running on latest paperclip don't get the deprecation warnings necessary for upgrading to v5. I think we need to revert this commit and release another patch release.

**Comment by sikachu** [comment]
@tute it should be done after `v5.0.0` is out, otherwise user will just keep getting message nagging them. 5.0 and 4.3.6 with deprecation message can go out at the same time.

**Comment by tute** [comment]
I see. I was inferring people will upgrade. What do you think of a 4.99 version, with only the deprecation warnings, à la rspec, so we explicitly state that it's the latest version when you want to move on to 5?

**Pull request merged**
