### PR TITLE
Update Appraisals

### PR DESCRIPTION
**Pull request by maclover7**

### CODE REVIEW

**Comment by maclover7** [comment]
@jferris @jyurek Ready to merge?

**Comment by mike-burns** [comment]
I cannot get Appraisal to work. @jferris @sikachu what am I doing wrong?

```
% bundle exec appraisal install
>> bundle check --gemfile='/home/mike/paperclip/gemfiles/3.2.gemfile' || bundle install --gemfile='/home/mike/paperclip/gemfiles/3.2.gemfile'
Your Gemfile lists the gem paperclip (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
You cannot specify the same gem twice coming from different sources.
You specified that paperclip (>= 0) should come from source at ../../ and source
at ../
Your Gemfile lists the gem paperclip (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
You cannot specify the same gem twice coming from different sources.
You specified that paperclip (>= 0) should come from source at ../../ and source
at ../
```

**Comment by maclover7** [comment]
@mike-burns That's weird - when Travis builds it is green...

**Comment by adamniedzielski** [comment]
I am facing the very same issue as @mike-burns

**Comment by jyurek** [comment]
This worked without issue for me, so I pulled it in. Thanks!

**Pull request closed without merging**
