### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Is it fine to add codebeat badge to README? 

codebeat is automated code review tool for Swift,Ruby,Go & Python that helps get instant feedback on code quality. 

"Quick wins" suggested by codebeat could be a nice candidate for a pull request and help other developers become contributors.

FYI. To be fully open and honest. I'm co-founder of codebeat.

### CODE REVIEW

**Comment by tute** [comment]
Hi @korzonek. It seems to me that this project provides something similar to CodeClimate. I'd change it if the service you propose is better. Is there a reason why we should move? Thanks!

**Comment by korzonek** [comment]
There are a few things that are not available in code climate and you can find in codebeat.

* _Multi-Language support for mobile and web applications_. We implemented all algorithms on our own. It means relatively quickly we can support more languages both for mobile and web. At this stage we analyse **Swift, Ruby, Python** and **Go**.
* _Correct namespace reporting for Ruby_ Please compare reports for Sinatra. Code Climate is using flay and flog gem which are known to misreport namespaces if there is more than one in the same ruby file. You can see an example [here](https://codeclimate.com/github/sinatra/sinatra/Sinatra::Base) where some duplications should be reported for `Sinatra::Templates` instead of `Sinatra::Base`. In codebeat it looks us some time to do it right :smile:  Please check [ratings for Sinatra](https://codebeat.co/projects/github-com-sinatra-sinatra/ratings) in codebeat.
* _Quick Wins_. After analysing your project we will suggest you issues in code with the biggest overall impact on your project's health. Try to refactor these hot spots first and see how your GPA improves.
* _Compare Changes_. In the stream of Recent Changes you will be able see what exactly caused your classes to improve or degrade.
* _Performance_ We are super proud of our backend. codebeat analysers are really fast :car: :car: :car: 

We are also about to release nice support for pull requests in codebeat.

**Comment by jeremywadsack** [comment]
CodeClimate supports Ruby, Python, PHP, CSS, ES/JavaScript, CoffeeScript, Go, RubyMotion, Haskell, SCSS, shell, vim, Node, Markdown, and more (see list [here](https://docs.codeclimate.com/docs/list-of-engines)).

CodeClimate provides a list of ["hotspots"](https://docs.codeclimate.com/docs/my-feed#hotspots) — things to address to make big differences in your GPA. It also shows critical issues on the dashboard (recently added).

As long as I've been using CodeClimate, it has shown [what changes](https://docs.codeclimate.com/docs/my-feed#whats-in-the-feed) caused the improvement or degradation of code quality.

I'm not affiliated with CodeClimate or Paperclip (and don't really have a strong recommendation for CodeClimate) but I just wanted to point out these out.

**Comment by tute** [comment]
I don't see reasons why we should move over yet, so I'll close this for now. Thanks!

**Pull request closed without merging**
