### PR TITLE
Up the aws-sdk v1 requiremet to >= 1.64.0

### PR DESCRIPTION
**Pull request by jyurek**
@tute This should address the concerns of making sure we don't have 0-length files anymore. I don't know if this is enough to cause a minor version bump though. Thoughts?

### CODE REVIEW

**Comment by tute** [comment]
Quoting your in https://github.com/thoughtbot/paperclip/issues/1955#issuecomment-141469883:

> I'm all for putting version restrictions on it, except for when I do, it seems that someone else has a problem with the way it got done. I don't really know what to do here.

What are those problems? Are they in this issue tracker?

**Comment by jyurek** [comment]
They are, as they're things people would report, but they're scattered. I think it's probably just best to do it, bite the bullet, and point to this as a reason if anyone has issues.

**Comment by tute** [comment]
Your call on merge then. To me this smells like a good reason to merge in a deprecation notice and call version 1 just buggy.

**Comment by tute** [comment]
Should we close this PR, and start a new "AWS V1" deprecation notice? See https://github.com/thoughtbot/paperclip/issues/1997#issuecomment-155987648

**Comment by tute** [comment]
AWS V1 has been removed: https://github.com/thoughtbot/paperclip/pull/2075. Closing this PR.

**Pull request closed without merging**
