### PR TITLE
Fix JRuby binary operator warning

### PR DESCRIPTION
**Pull request by dzsibi**
Fixes the following warning shown by JRuby 9.1.6.0:

gems/paperclip-5.1.0/lib/paperclip/storage/filesystem.rb:49: warning: `&' after local variable or literal is interpreted as binary operator even though it seems like argument prefix

### CODE REVIEW

**Comment by tute** [comment]
Thanks! Can you please push against latest master, to check if CI passes? Thanks!

**Comment by dzsibi** [comment]
Here ya go.

**Comment by tute** [comment]
Excellent, thank you!

**Comment by YavorIvanov** [comment]
I just realize that we are still using the gem from the git repo for this fix.
Should we not release 5.1.1 with this?

**Pull request merged**
