### PR TITLE
Destroy callback: add fallback for ORMs which do not support transactions

### PR DESCRIPTION
**Pull request by johnnyshields**
Refer to comments on https://github.com/thoughtbot/paperclip/commit/a01677f58762394c2915eb512fe2f69aec6fbcf5

### CODE REVIEW

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue? If so, can you please rebase your PR and make sure everything is passing? Thanks!

**Comment by johnnyshields** [comment]
There needs to be a broader push to get first-class Mongoid support in Paperclip. Currently there are several gems floating around which monkey-patch Paperclip for Mongoid, which is not ideal.

**Comment by jyurek** [comment]
Well, it seems I pulled in another PR that addresses this without realizing this already did. Does 17ecc58 fix this problem?

**Comment by johnnyshields** [comment]
@jyurek yes https://github.com/thoughtbot/paperclip/commit/17ecc58ab2162675638a3148602f33030ab8ccf0 fixes this, so closing this PR.

**Pull request closed without merging**
