### PR TITLE
defualt permission should assume aws v2 if both aws versions are in use

### PR DESCRIPTION
**Pull request by betesh**

### CODE REVIEW

**Comment by tute** [comment]
These conditionals would not exist if we had two different files, one for each branch. This PR doesn't change behavior or simplify the code, so I won't merge it for now. I am very interested in simplifying this into two files: `s3-aws1.rb`,  and `s3-aws2.rb`. We can merge that PR if you'd like to work on it!

Thank you very much for your contribution.

**Comment by betesh** [comment]
**This is a fix to code that has already been merged into master.**

@tute I assume from your later comment https://github.com/thoughtbot/paperclip/issues/1974#issuecomment-138757919 that you do plan on merging this after all?

The question of separate classes was brought up already in the discussion on the PR that introduced AWS v2 support: https://github.com/thoughtbot/paperclip/pull/1903#issuecomment-113193016

**Comment by tute** [comment]
Thanks! All done then. Where did you read about the upcoming deprecation of v1? I couldn't find docs related to that.

**Comment by betesh** [comment]
@tute, I didn't say anything about deprecation.

Are you merging this?

**Comment by tute** [comment]
> @tute, I meant that eventually paperclip will want to deprecate AWS v1 support. I was assuming (correct me if I'm wrong) that once paperclip publishes a gem that supports both, we'll want to deprecate AWS v1 support a few versions later. (Reading that comment again now, I was also confused by what I meant.)

We have a specific issue to discuss wether AWS v1 should be deprecated: https://github.com/thoughtbot/paperclip/issues/1997.

**Comment by betesh** [comment]
Thank you for pointing me to that ticket.

However, it has nothing to do with whether this PR should be merged.  There is a bug in master.  It should be fixed before we publish a gem.

**Comment by betesh** [comment]
@tute I still don't understand why this was closed.  I have rebased it onto the latest master, where it is still an issue

**Comment by tute** [comment]
I just came from vacations, will look into it soon.

**Comment by tute** [comment]
Hi @betesh! I can't reopen the PR, because the branch seems to be gone from your repo. Want to pusblish it so we reopen?

But before, why is this change necessary? Thank you!

**Comment by betesh** [comment]
AWS v1: 'public_read'
AWS v2: 'public-read'

If you have both in you Gemfile, we use v2 but we use public_read, which is inconsistent and means that the default configuration is broken.

**Pull request closed without merging**
