### PR TITLE
Updated the `build missing styles` Capistrano task

### PR DESCRIPTION
**Pull request by urbas**
The task (as specified in the current form) did not work for me (on Rails 4.2.0 and Capistrano 3.3.5 with rbenv). I changed the task so that it uses the same standards as Capistrano's own tasks.

This now works for my setup.

### CODE REVIEW

**Comment by maclover7** [comment]
Hi @urbas ! Is this still an issue? If so, can you please rebase your PR and make sure everything is passing? Thanks!

**Comment by urbas** [comment]
Hey @maclover7, yes, this PR is still valid. I have rebased it now.

Btw, this change is only to the `README.md` file. So no code should break.

**Comment by maclover7** [comment]
@mike-burns @jyurek @jferris Thoughts on this?

**Comment by urbas** [comment]
Oh, btw, I based the changes on this: https://github.com/capistrano/rails/blob/master/lib/capistrano/tasks/assets.rake#L54

**Comment by maclover7** [comment]
@mike-burns @jyurek @jferris Thoughts on this?

**Pull request merged**
