### PR TITLE
Output shorter but still useful error message

### PR DESCRIPTION
**Pull request by ajh**
Before this the error message was sometimes millions of characters long. For example, for a log file that only has one 'Content Type Spoof' error in it:

    $ grep -h 'Content Type Spoof' log/test.log | wc -m
    5690433

That's 5.6 million characters for that single error message. Too big!

I didn't add a test. The code path that generates this error message already has plenty of coverage.

### CODE REVIEW

**Comment by ajh** [comment]
This is related to #1979

**Comment by tute** [comment]
Thank you! What was the message logged before, and what is now?

Style: can you change `collect` by `map`?

Thanks!

**Comment by ajh** [comment]
Sure, Here's the difference in messages:

    [paperclip] Content Type Spoof: Filename a.csv (application/octet-stream from Headers, [#<MIME::Type::Columnar:0x007f9f90f89fa8 @container=#<MIME::Types:0x007f9f90b09d98 ... snip millions of characters of output here ...>], @content_type="text/csv", @raw_media_type="text", @raw_sub_type="csv", @simplified="text/csv", @i18n_key="text.csv", @media_type="text", @sub_type="csv", @extensions=["csv"]>] from Extension), content type discovered from file command: application/zip. See documentation to allow this combination.

Now becomes:

    [paperclip] Content Type Spoof: Filename a.csv (application/octet-stream from Headers, ["text/comma-separated-values", "text/csv"] from Extension), content type discovered from file command: application/zip. See documentation to allow this combination.

**Comment by tute** [comment]
Thank you! :+1:

**Comment by dgilperez** [comment]
:clap: :beers: :heart:

**Pull request closed without merging**
