### PR TITLE
fix S3 adapter runtime constant definition not being thread-safe

### PR DESCRIPTION
**Pull request by erkki**
After debugging seemingly random exceptions on DEFAULT_PERMISSION not being defined in a threaded downloader, it became clear the S3 adapter is not thread safe.

Here is a sample run with 2 threads and debug prints:
```
#<Thread:0x007f925d34eeb8> before defined? check AWS_CLASS
#<Thread:0x007f925d34eeb8> before const_set AWS_CLASS
#<Thread:0x007f925d34eeb8> after const_set AWS_CLASS
#<Thread:0x007f925d34ed78> before defined? check AWS_CLASS
#<Thread:0x007f925d34ed78> before usage of const DEFAULT_PERMISSION
#<Thread:0x007f925d34eeb8> before const_set DEFAULT_PERMISSION
#<Thread:0x007f925d34eeb8> after const_set DEFAULT_PERMISSION
#<Thread:0x007f925d34eeb8> before usage of const DEFAULT_PERMISSION
#<Thread:0x007f925d34eeb8> after usage of const DEFAULT_PERMISSION
```
The added Thread#exclusive block is probably too wide and blunt of an fix but should be fine until a better one comes along.

Decided to use 10 threads in the spec after making sure of a good-enough failure rate (it is still possible to get false-positives but they should be rare).

### CODE REVIEW

**Comment by erkki** [comment]
Any feedback here? I'm looking at the few travis failures, at least one  seems non-related.

**Comment by tute** [comment]
Hey, thank you! Is this still relevant after recent changes to this file? If so, can you please rebase your changes? Thank you!

**Comment by erkki** [comment]
Sure thing, let me check asap and get back to you, thanks!

**Comment by tute** [comment]
This code has been removed since then. Thank you for your time and sharing your work! ❤️

**Comment by erkki** [comment]
Sorry about the delay in response, yes, confirmed that this is not an issue with the code removed. Thanks for handling :)

**Pull request closed without merging**
