### PR TITLE
Docs: Provide example for s3_host_name

### PR DESCRIPTION
**Pull request by dijonkitchen**
Gives an example, since not everyone knows the format required.

### CODE REVIEW

**Comment by jhack32** [comment]
https://github.com/thoughtbot/paperclip#defaults

**Comment by dijonkitchen** [comment]
@jhack32 how's that relevant to this PR?

**Comment by dijonkitchen** [comment]
This is still relevant!

**Comment by obelich** [comment]
i have problem using this :( it dont working give a Aws::S3::Errors::Http405Error ():
i have in Gemfile
gem 'aws-sdk', '~> 2'
gem 'paperclip', :git => "git://github.com/thoughtbot/paperclip.git"


`
Paperclip::Attachment.default_options[:storage] = :s3
Paperclip::Attachment.default_options[:s3_region] = "us-west-1"
Paperclip::Attachment.default_options[:s3_protocol] = "http"
Paperclip::Attachment.default_options[:url] = ":s3_domain_url"
Paperclip::Attachment.default_options[:path] = ":class/:attachment/:id_partition/:style/:filename"

Paperclip::Attachment.default_options[:s3_credentials] = {
    bucket: ENV['S3_BUCKET'],
    access_key_id: ENV['S3_ACCESS_KEY'],
    secret_access_key: ENV['S3_SECRET_KEY'],
    s3_host_name: ENV['S3_HOST_NAME']
}

Paperclip::Attachment.default_options[:s3_options] = {
    force_path_style: true,
    endpoint: 'http://files.jelp.io.s3-website-us-west-1.amazonaws.com'
}


`

**Comment by dijonkitchen** [comment]
@obelich I'm not sure this is the right place to put your problem unless it has to do with the `s3_host_name`. 

I'd check the installation instructions in the [Readme](https://github.com/thoughtbot/paperclip/blob/master/README.md) (for example, do you realy need the latest `paperclip` version on git?), https://github.com/thoughtbot/paperclip#defaults, and http://www.rubydoc.info/gems/paperclip/Paperclip/Attachment.default_options

**Pull request merged**
