### PR TITLE
Fixes #1453 (Squashed)

### LINKED ISSUE #1453: If call @model.file.url() on a non saved istance get a url instead of nil
Hi,

In my action controller call `render 'action'` if model validations fails.

In the `action` view have
```
<div id="preview" data-preview-url="<%= @model.preview.url %>">
```
that return good url if `@model` is saved on db, bad url without :`id` part(obviously) if `@model` is not stored to db. Have to return `nil` in this case or I'm wrong?

### PR DESCRIPTION
**Pull request by byterussian**

### CODE REVIEW

**Comment by maclover7** [comment]
Hi @byterussian! Can you please fix the Hound style guide comments? Thanks!

**Comment by byterussian** [comment]
Done, there is a method to squash the commits without open a new PR? I've already squashed and pushed with --force option but nothing.

**Comment by maclover7** [comment]
@byterussian How did you try and squash?

**Comment by byterussian** [comment]
Never mind, I've just tried again and now works. :smile:

**Comment by maclover7** [comment]
@jferris @jyurek @mike-burns - Thoughts on this?

**Comment by mike-burns** [comment]
Link to the bug: #1453.

Returning `nil` seems rather unpleasant. I'm tempted to say that the solution to the bug is "don't do that."

(And as the author of Wrapped, I liked to advocate for #url returning a wrapped object instead.)

@jferris @jyurek do you have more opinions on this?

**Comment by byterussian** [comment]
Hi @mike-burns, in ActiveRecord a `Model.new` object returns `nil` for almost every attribute/field, IMHO there is no reason for paperclip to returns a nonexistent url.

**Comment by jyurek** [comment]
While I agree with @mike-burns in principle, the reality is that we use `nil` all the time, and, IMHO, not using it here would be more surprising than using it. This looks ok to me, and once the tests are done running, I'll pull it in.

**Comment by jyurek** [comment]
Merged this in. Thanks!

**Comment by fw42** [comment]
I believe this PR might have introduced a new bug: https://github.com/thoughtbot/paperclip/issues/1930

**Pull request closed without merging**
