### PR TITLE
Updated the capitalization in the titles

### PR DESCRIPTION
**Pull request by elliefichtelman**
Some of the titles were inconsistent in capitalization.

### CODE REVIEW

**Comment by elliefichtelman** [comment]
This was my first pull request, so it was very simple.

**Comment by tute** [comment]
Thanks so much! Those titles are also inconsistent down in the content, in `### Checking a file exists` for example. Can you update those as well please?
Thanks!

**Comment by tute** [comment]
Ping @elliefichtelman: don't forget! The reason we need the content to be updated is that the index is generated automatically from them. Let me know if I can help you. Thanks!

**Comment by tute** [comment]
I merged it in in https://github.com/thoughtbot/paperclip/commit/7c81e7813e75950d111885b44d33c08358e5e46c. Thank you! :)

**Comment by elliefichtelman** [comment]
My apologies, these notifications got buried in my emails. Thank you, I look forward to contributing in the future after learning a bit more! :) Again, my apologies for not seeing this until now!

**Pull request closed without merging**
